# azure-pipelines.yml
trigger:
- main 

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  projectFile: 'DailyPlanner/DailyPlanner.csproj' 
  
stages:
- stage: Build
  displayName: Build and Publish Artifact
  jobs:
  - job: BuildJob
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: '$(projectFile)'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '$(projectFile)'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command: 'publish'
        publishWebProjects: false 
        projects: '$(projectFile)'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Upload Artifact'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
        
- stage: Deploy
  displayName: Deploy to Azure App Service
  # üèÜ FIX: Tell the Deploy stage to wait for the Build stage 
  dependsOn: Build
  
  jobs:
  - job: DeployJob
    # Note: We removed the 'dependsOn: BuildJob' from here, as the stage dependency handles it.
    steps:
    - task: DownloadBuildArtifacts@1
      displayName: 'Download Artifact'
      inputs:
        artifactName: 'drop'
        downloadPath: '$(System.DefaultWorkingDirectory)'
        
    - task: AzureWebApp@1
      displayName: 'Azure Web App Deploy'
      inputs:
        azureSubscription: 'DailyPlannerDevOpsSC' 
        appName: 'dailyplannercse325' 
        package: '$(System.DefaultWorkingDirectory)/drop/**/*.zip' 
        appType: 'webApp'